SHOW CON_NAME;

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER admin IDENTIFIED BY admin;

GRANT CREATE SESSION TO admin;
GRANT CREATE USER, ALTER USER, DROP USER TO admin;
GRANT CREATE ROLE TO admin;
GRANT GRANT ANY ROLE TO admin;
GRANT CREATE TABLESPACE, ALTER TABLESPACE, DROP TABLESPACE TO admin;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO admin;
GRANT CREATE SEQUENCE, CREATE TRIGGER, CREATE SYNONYM TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;
GRANT GRANT ANY OBJECT PRIVILEGE TO admin;

COMMIT;

--To check the tablespaces the guest user has
SELECT username, default_tablespace, temporary_tablespace
FROM dba_users
WHERE username = 'GUEST_USER';

-- Create public synonym for the top user view
CREATE OR REPLACE PUBLIC SYNONYM TOP_USERS FOR tw1.top_author_by_tweets;

-- Final commit
COMMIT;